name: BetterUhc
main: me.birajrai.BetterUhc
version: @version@
description: Automates UHC games on a dedicated server
author: Neppixel
softdepend: [WorldEdit,Vault,ProtocolLib]
api-version: 1.13
commands:
  betteruhc:
    description: "Type '/betteruhc help' to see a list of commands"
    usage: "/betteruhc <sub-command> (Debug command only!)"
  chat:
    description: "Type '/chat' to toggle global chat"
    usage: "/chat"
    aliases: [c]
  teleport:
    description: "Type '/teleport <player>' to teleport to your teammates while spectating"
    usage: "/teleport <player>"
    aliases: [tp]
  start:
    description: "This command is used to toggle force starting of the game"
    usage: /<command>
    permission: "betteruhc.commands.start"
    aliases: [start, forcestart]
  scenarios:
    description: "This command is used to view and toggle scenarios."
    usage: /<command>
    aliases: [game, settings, uhc]
  teaminventory:
    description: "This command is used to open team inventory."
    usage: /<command>
    aliases: [ti, backpack, bp]
  hub:
    description: "This command is used to return back to the hub."
    usage: /<command>
    aliases: [lobby, leave, spawn]
  iteminfo:
    description: "This command is used to get the right item data for the config."
    usage: "/<command> while holding a item."
    permission: "betteruhc.commands.iteminfo"
  revive:
    description: "You can use this command to let a death player respawn in the game."
    usage: /<command> <player>
    permission: "betteruhc.commands.revive"
  seed:
    description: "This command is overridden from the vanilla /seed command to stop confusion."
    usage: /<command>
    permission: "minecraft.command.seed"
  crafts:
    description: "This command is used to open the custom crafting recipes menu"
    usage: /<command>
    aliases: [craft, recipe, recipes]
  top:
    description: "This command teleports players to the highest block above their head"
    usage: /<command>
    permission: "betteruhc.commands.top"
  spectate:
    description: "This command can be used to set yourself as spectator at the start of the game."
    usage: /<command>
    permission: "betteruhc.commands.spectate"
  upload:
    description: "This command can be used to upload a certain file to hastebin.com."
    usage: /<command> <file-type>
    permission: "betteruhc.commands.upload"
  deathmatch:
    description: "This command can be used to force-start the deathmatch."
    usage: /<command> start
    permission: "betteruhc.commands.deathmatch"
  team:
    description: "Used to manage teams."
    usage: /<command> <sub-command>